//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bienes_Raices_HAXA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public long idCita { get; set; }
        public long idUsuario { get; set; }
        public long idPropiedad { get; set; }
        public string titulo { get; set; }
        public string fechaInicio { get; set; }
        public string fechaFinal { get; set; }
    
        public virtual Propiedad Propiedad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
