//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bienes_Raices_HAXA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagenes
    {
        public long idImagen { get; set; }
        public long idPropiedad { get; set; }
        public string link { get; set; }
    
        public virtual Propiedad Propiedad { get; set; }
    }
}
